# Pre-commit hooks to ensure consistent formatting
# Run `pre-commit install` to set up the git hook
# Run `pre-commit run --all-files` to check all files manually

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(data/|models/|archive/)
      - id: end-of-file-fixer
        exclude: ^(data/|models/|archive/)
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=5000"]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: ["--line-length=100"]
        language_version: python3.11

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile=black", "--line-length=100"]
